In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# **Initialise Tensors**

In [2]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.rand(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.5565, 0.2997],
        [0.3464, 0.5656],
        [0.0885, 0.0178]])


In [5]:
x = torch.empty(3, 2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[6.7941e+22, 1.0244e-11],
        [4.2887e-08, 6.7504e-07],
        [3.3975e+21, 5.1173e+22]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
x = torch.linspace(0, 1, steps = 5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [7]:
x = torch.tensor([[3,2]
                 ,[5,3]
                 ,[6,4]])
print(x)

tensor([[3, 2],
        [5, 3],
        [6, 4]])


# **Slicing Tensors**

In [8]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 3, 4])
tensor([3, 2])


In [9]:
y = x[1,1]
print(y)
print(y.item())

tensor(3)
3


# **Reshaping Tensors**

In [10]:
print(x)
y = x.view(2, 3)
print(y)

tensor([[3, 2],
        [5, 3],
        [6, 4]])
tensor([[3, 2, 5],
        [3, 6, 4]])


In [12]:
y = x.view(6, -1)
print(y)

tensor([[3],
        [2],
        [5],
        [3],
        [6],
        [4]])


# **Simple Tensor Operations**

In [13]:
x = torch.ones([3, 2])
y = torch.ones([3, 2])
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [15]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


# **NumPy and Pytorch**

In [18]:
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))

[0.44853946 0.05700867 1.29310198 0.93349878 0.40564737]
<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [20]:
np.add(a, 1, out = a)
print(a)
print(a_pt)

[1.44853946 1.05700867 2.29310198 1.93349878 1.40564737]
tensor([1.4485, 1.0570, 2.2931, 1.9335, 1.4056], dtype=torch.float64)


In [23]:
%%time
for i in range(100):
    a = np.random.randn(100, 100)
    b = np.random.randn(100, 100)
    c = np.matmul(a, b)

CPU times: total: 93.8 ms
Wall time: 137 ms


In [24]:
%%time
for i in range(100):
    a = torch.rand([100,100])
    b = torch.rand([100,100])
    c = torch.matmul(a, b)

CPU times: total: 0 ns
Wall time: 66.7 ms


In [25]:
%%time
for i in range(10):
    a = np.random.randn(10000, 10000)
    b = np.random.randn(10000, 10000)
    c = a + b

CPU times: total: 49.4 s
Wall time: 1min 29s


In [26]:
%%time
for i in range(10):
    a = torch.rand([10000,10000])
    b = torch.rand([10000,10000])
    c = a + b

CPU times: total: 12.5 s
Wall time: 21.3 s


# **CUDA Support**

In [2]:
print(torch.cuda.device_count())

1


In [3]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

NVIDIA GeForce MX550


In [4]:
cuda = torch.device('cuda:0')

In [31]:
a = torch.ones(3, 2, device = cuda)
b = torch.ones(3, 2, device = cuda)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [33]:
%%time
for i in range(10):
    a = np.random.randn(10000, 10000)
    b = np.random.randn(10000, 10000)
    np.add(b, a)

CPU times: total: 45.9 s
Wall time: 1min 30s


In [34]:
%%time
for i in range(10):
    a = torch.rand(10000, 10000)
    b = torch.rand(10000, 10000)
    b.add_(a)

CPU times: total: 11.2 s
Wall time: 19.9 s


In [35]:
%%time
for i in range(10):
    a = torch.rand(10000, 10000, device = cuda)
    b = torch.rand(10000, 10000, device = cuda)
    b.add_(a)

CPU times: total: 62.5 ms
Wall time: 457 ms


In [10]:
%%time
for i in range(10):
    a = torch.rand(10000, 10000, device = cuda)
    b = torch.rand(10000, 10000, device = cuda)
    c = torch.matmul(a, b)

CPU times: total: 0 ns
Wall time: 8.12 ms


# **Autograd**

In [5]:
x = torch.ones([3, 2], requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [7]:
z = y*y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [8]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [9]:
t.backward()

In [10]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [12]:
x = torch.ones([3, 2], requires_grad = True)
y = x + 5
r = 1/ (1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [14]:
x = torch.ones([3, 2], requires_grad = True)
y = x + 5
r = 1/ (1 + torch.exp(-y))
a = torch.ones([3, 2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


# **Autograd example**

In [15]:
x = torch.randn([20,1], requires_grad = True)
y = 3*x - 2

In [16]:
w = torch.tensor([1.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
y_bar = w*x + b
loss = torch.sum((y_bar - y)**2)

In [17]:
print(loss)

tensor(316.8991, grad_fn=<SumBackward0>)


In [18]:
loss.backward()

In [19]:
print(w.grad, b.grad)

tensor([-91.8843]) tensor([150.0098])


# **In Loop**

In [21]:
lr = 0.01
w = torch.tensor([1.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
print(w.item(), b.item())
for i in range(10):
    x = torch.randn([20,1], requires_grad = True)
    y = 3*x - 2
    y_bar = w*x + b
    loss = torch.sum((y_bar - y)**2)
    loss.backward()
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(w.item(), b.item())

1.0 1.0
1.32503342628479 0.32770127058029175
1.6329081058502197 -0.5417454838752747
2.0426759719848633 -1.2446149587631226
2.4670867919921875 -1.5493930578231812
2.565831184387207 -1.7339204549789429
2.7002625465393066 -1.8435373306274414
2.852740526199341 -1.948807954788208
2.8870601654052734 -1.9660980701446533
2.933042287826538 -1.9936093091964722
2.9687697887420654 -2.0003671646118164


In [9]:
lr = 0.001
N = 10000
epochs = 200
w = torch.rand([N], requires_grad = True)
b = torch.ones([1], requires_grad = True)
print(torch.mean(w).item(), b.item())  
for i in range(epochs):
    x = torch.randn([N])
    y = torch.dot(3*torch.ones([N]), x) - 2
    y_bar = torch.dot(w, x) + b
    loss = torch.sum((y_bar - y)**2)
    loss.backward()
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(torch.mean(w).item(), b.item())  

0.49867942929267883 1.0
0.5045997500419617 1.5307636260986328
0.5047336220741272 1.4836132526397705
0.5053952932357788 1.1708838939666748
0.5058832764625549 1.040334939956665
0.5067720413208008 1.2273499965667725
0.5115174055099487 0.7573897838592529
0.5163638591766357 1.2878062725067139
0.5162914991378784 1.3358049392700195
0.5339794158935547 0.3418659567832947
0.5524488091468811 -0.4156680703163147
0.5536306500434875 -0.2247699350118637
0.5558272004127502 0.508055567741394
0.5625354647636414 0.9241025447845459
0.5697919130325317 0.26532286405563354
0.5698040127754211 0.2591307461261749
0.5698081254959106 0.26051056385040283
0.5697841048240662 0.23253770172595978
0.5753366351127625 0.7272738814353943
0.5773356556892395 0.38012242317199707
0.5766387581825256 1.0735769271850586
0.5787481665611267 1.4029954671859741
0.583806037902832 2.2783150672912598
0.5837944149971008 2.2156527042388916
0.5853345990180969 2.333866834640503
0.5824567675590515 1.905122995376587
0.5823519229888916 1.8956