<a href="https://colab.research.google.com/github/revanth-eranki/dl-notebooks/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Numpy Basics

In [ ]:
n = 1

In [ ]:
list_ = list(range(n))

In [ ]:
%%time
for i in range(n):
  list_[i]=list_[i]*list_[i]

CPU times: user 27.6 s, sys: 72.9 ms, total: 27.7 s
Wall time: 28.2 s


In [ ]:
%%time
list_=[i*i for i in list_]

CPU times: user 8.46 s, sys: 3.29 s, total: 11.8 s
Wall time: 12.2 s


In [ ]:
%%time
list_=map(lambda x: x*x,list_)

CPU times: user 8 µs, sys: 0 ns, total: 8 µs
Wall time: 12.2 µs


In [ ]:
%%time
arr = np.arange(n)
arr = arr*arr

CPU times: user 233 ms, sys: 548 ms, total: 782 ms
Wall time: 774 ms


we index dimensions backwards in the order we added them

In [ ]:
arr = np.array([0,1,2,8])

In [ ]:
print(arr,type(arr))

[0 1 2 8] <class 'numpy.ndarray'>


In [ ]:
arr.shape

(4,)

In [ ]:
arr.size()

4

In [ ]:
arr.ndim

1

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.itemsize

8

In [ ]:
arr = np.array([0.0,1,2,8])

In [ ]:
arr

array([0., 1., 2., 8.])

In [ ]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr3d = np.array([
    [   [1,2,5],
        [6,7,8]
    ],

    [
        [10,11,13],
        [14,15,16]
    ]
])

In [ ]:
arr3d

array([[[ 1,  2,  5],
        [ 6,  7,  8]],

       [[10, 11, 13],
        [14, 15, 16]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
np.ones((3,4)) # 1st arg is a tuple size

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
1732*np.ones((3,4))

array([[1732., 1732., 1732., 1732.],
       [1732., 1732., 1732., 1732.],
       [1732., 1732., 1732., 1732.]])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.random.randn(2,2)  #series of numbers from a normal distribution which have mean =0 and sd , variance 1

array([[-0.91222871,  1.33892649],
       [ 1.41829974, -0.39557755]])

In [ ]:
np.random.rand(2,3) #numbers are uniformly  distributed  in btw 0 to 1

array([[0.67161326, 0.81592932, 0.79793411],
       [0.49695583, 0.11787542, 0.96682269]])

In [ ]:
np.random.randint(0,10,(2,3,4))  #start,end,size

array([[[5, 6, 2, 5],
        [8, 1, 0, 4],
        [4, 0, 2, 2]],

       [[8, 1, 9, 2],
        [4, 2, 7, 8],
        [8, 4, 9, 8]]])

In [ ]:
np.arange(4,50,5)  #start,end,stepsize

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [ ]:
np.linspace(4,50,5) #it is like cut 5 numbers of equal space btw 4 and 50

array([ 4. , 15.5, 27. , 38.5, 50. ])

conversion btw data types

In [ ]:
str_arr=np.array(['2','3','5'])

In [ ]:
arr = np.array(str_arr,dtype='float')

In [ ]:
arr

array([2., 3., 5.])

# indexing

In [ ]:
arr3d = np.array([
    [   [1,2,5],
        [6,7,8]
    ],

    [
        [10,11,13],
        [14,15,16]
    ]
])

In [ ]:
arr3d

array([[[ 1,  2,  5],
        [ 6,  7,  8]],

       [[10, 11, 13],
        [14, 15, 16]]])

In [ ]:
arr3d[0,0,0]

1

In [ ]:
arr3d[1,0,2] #z,y,x axis

13

In [ ]:
arr3d[0,:,:]

array([[1, 2, 5],
       [6, 7, 8]])

In [ ]:
arr3d[:,1,:]

array([[ 6,  7,  8],
       [14, 15, 16]])

In [ ]:
arr3d[:,:,0:2]

array([[[ 1,  2],
        [ 6,  7]],

       [[10, 11],
        [14, 15]]])

In [ ]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[ True, False, False],
        [ True, False,  True]]])

In [ ]:
arr3d[arr3d%2==0] # show me those values which satisfies condition

array([ 2,  6,  8, 10, 14, 16])

In [ ]:
arr3d[(arr3d%2==0) & (arr3d>6) ]

array([ 8, 10, 14, 16])

In [ ]:
arr_slice =arr3d[:,:,0:2]

In [ ]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [ ]:
arr_slice.ndim

3

In [ ]:
arr_slice.shape

(2, 2, 2)

In [ ]:
arr_slice[0,0,0] = 1729

In [ ]:
print(arr_slice)

[[[1729    2]
  [   6    7]]

 [[  10   11]
  [  14   15]]]


In [ ]:
arr3d

array([[[1729,    2,    5],
        [   6,    7,    8]],

       [[  10,   11,   13],
        [  14,   15,   16]]])

In [ ]:
arr_slice =np.copy(arr3d[:,:,0:2])

In [ ]:
arr_slice[0,0,0]=1

In [ ]:
arr3d

array([[[1729,    2,    5],
        [   6,    7,    8]],

       [[  10,   11,   13],
        [  14,   15,   16]]])

In [ ]:
arr = np.random.randint(0,10,5)

In [ ]:
arr

array([2, 6, 4, 9, 3])

In [ ]:
my_indices=[1,3,4]

In [ ]:
arr[my_indices]

array([6, 9, 3])

# Numpy operations

In [ ]:
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(3,4)

In [ ]:
arr1

array([[0.32269169, 0.69206246, 0.15530431, 0.79808958],
       [0.68136566, 0.2847849 , 0.86558177, 0.38655631],
       [0.54303613, 0.02492446, 0.92882449, 0.59450728]])

In [ ]:
arr2

array([[0.91947532, 0.91064152, 0.06824789, 0.10970412],
       [0.14225105, 0.13178406, 0.56169576, 0.45217922],
       [0.60345302, 0.91803398, 0.84480351, 0.46006357]])

In [ ]:
arr1 + arr2

array([[1.242167  , 1.60270399, 0.2235522 , 0.90779371],
       [0.82361672, 0.41656896, 1.42727753, 0.83873553],
       [1.14648915, 0.94295844, 1.773628  , 1.05457085]])

In [ ]:
arr1 / arr2

array([[0.35095198, 0.75997244, 2.27559157, 7.2749279 ],
       [4.78988134, 2.1609966 , 1.54101531, 0.85487412],
       [0.89988137, 0.02714982, 1.09945623, 1.29222855]])

In [ ]:
arr1*arr2 # point wise multiplication

array([[0.29670704, 0.63022082, 0.01059919, 0.08755372],
       [0.09692498, 0.03753011, 0.48619361, 0.17479273],
       [0.3276968 , 0.0228815 , 0.78467419, 0.27351114]])

In [ ]:
np.exp(arr1)

array([[1.38083955, 1.99783174, 1.16801335, 2.22129328],
       [1.97657522, 1.32947603, 2.37638819, 1.47190328],
       [1.7212248 , 1.02523767, 2.53153158, 1.81213785]])

In [ ]:
np.log(np.exp(arr1))

array([[0.32269169, 0.69206246, 0.15530431, 0.79808958],
       [0.68136566, 0.2847849 , 0.86558177, 0.38655631],
       [0.54303613, 0.02492446, 0.92882449, 0.59450728]])

In [ ]:
np.sin(arr1)

array([[0.31712046, 0.63812649, 0.15468076, 0.71602378],
       [0.62985434, 0.28095102, 0.76147249, 0.37700107],
       [0.51673773, 0.02492187, 0.80091663, 0.56010064]])

In [ ]:
np.sqrt(arr1)

array([[0.56805958, 0.83190292, 0.39408668, 0.8933586 ],
       [0.82544876, 0.53365242, 0.93036647, 0.62173653],
       [0.73690985, 0.15787481, 0.96375541, 0.77104298]])

In [ ]:
arr_inv = 1/arr1
print(arr_inv)

[[ 3.09893327  1.44495628  6.43897117  1.25299217]
 [ 1.46764073  3.51142211  1.15529236  2.58694522]
 [ 1.84149809 40.12123764  1.07662967  1.68206519]]


In [ ]:
arr = np.zeros((3,4))
arr_inv = 1 / arr
print(arr_inv) #infinity

[[inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]]


<ipython-input-95-b3c28cf14a6d>:2: RuntimeWarning: divide by zero encountered in divide
  arr_inv = 1 / arr


In [ ]:
np.isinf(arr_inv[0,0])

True

In [ ]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#**Reshape**

In [ ]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1.shape

(6,)

In [ ]:
arr1=arr1.reshape(3,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr1.shape

(3, 2)

In [ ]:
arr2=np.arange(6).reshape((3,2))

In [ ]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arr2[0].reshape((1,2))

array([[0, 1]])

# Broadcasting

In [ ]:
arr1 + arr2[0].reshape((1,2))   #(3,2) + (1,2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [ ]:
arr2[:,0].reshape((3,1))

array([[0],
       [2],
       [4]])

In [ ]:
arr1 + arr2[:,0].reshape((3,1)) #(3,2) +(3,1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr1 = np.arange(24).reshape((2,3,4))

In [ ]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr2 = np.ones((1,4))
arr1 + arr2      #(2,3,4) + (1,4)  check from back (from 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [ ]:
arr1 = np.arange(4)
arr2 = np.arange(5)
arr1 + arr2

ValueError: ignored

In [ ]:
arr1.reshape(4,1) + arr2  #(4,1) + (5)


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr1.T

array([0, 1, 2, 3])

# File Handling

In [ ]:
planets_small = np.loadtxt("planets_small.txt",skiprows=1,usecols=(1,2,3,4,5,6,7,8,9))

In [ ]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [ ]:
planets_small.ndim

2

In [ ]:
planets_small.shape

(3, 9)

genfromtxt converts unknown to nan(not a number) and does not show error

In [ ]:
planets = np.genfromtxt("planets.txt",skip_header=1,usecols=[1,2,3,4,5,6,7,8,9])

In [ ]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
planets.shape

(20, 9)

In [ ]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [ ]:
planets_new = np.nan_to_num(planets,nan =-1)

In [ ]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
np.savetxt('planets_new.txt',planets_new,
           delimiter=',')

In [ ]:
np.save("planets_new",planets_new)  # will be saved as .npy file not as txt file

In [ ]:
!ls # exclamation mark : runs all unix commands on virtual machine

planets_new.npy  planets_new.txt  planets_small.txt  planets.txt  sample_data


In [ ]:
!ls -lh #compare space of .npy,.txt files.

total 24K
-rw-r--r-- 1 root root 1.6K Oct 21 17:02 planets_new.npy
-rw-r--r-- 1 root root 4.5K Oct 21 16:59 planets_new.txt
-rw-r--r-- 1 root root  257 Oct 21 16:52 planets_small.txt
-rw-r--r-- 1 root root 1.5K Oct 21 16:52 planets.txt
drwxr-xr-x 1 root root 4.0K Oct 19 16:36 sample_data


In [ ]:
arr1 = np.random.rand(1000,10)
arr2 = np.random.rand(100,4)
arr3 = np.random.rand(200,5)

In [ ]:
np.savez("many_arrays",arr1,arr2,arr3) # saving many arrays

In [ ]:
!ls -l

total 116
-rw-r--r-- 1 root root 91948 Oct 21 17:09 many_arrays.npz
-rw-r--r-- 1 root root  1568 Oct 21 17:02 planets_new.npy
-rw-r--r-- 1 root root  4512 Oct 21 16:59 planets_new.txt
-rw-r--r-- 1 root root   257 Oct 21 16:52 planets_small.txt
-rw-r--r-- 1 root root  1455 Oct 21 16:52 planets.txt
drwxr-xr-x 1 root root  4096 Oct 19 16:36 sample_data


In [ ]:
arrs = np.load('many_arrays.npz') #loading files

In [ ]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [ ]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [ ]:
arrs['arr_0'].shape

(1000, 10)

In [ ]:
np.savez_compressed('many_arrays_compressed',arr1,arr2,arr3)

In [ ]:
!ls -lh

total 204K
-rw-r--r-- 1 root root  85K Oct 21 17:13 many_arrays_compressed.npz
-rw-r--r-- 1 root root  90K Oct 21 17:09 many_arrays.npz
-rw-r--r-- 1 root root 1.6K Oct 21 17:02 planets_new.npy
-rw-r--r-- 1 root root 4.5K Oct 21 16:59 planets_new.txt
-rw-r--r-- 1 root root  257 Oct 21 16:52 planets_small.txt
-rw-r--r-- 1 root root 1.5K Oct 21 16:52 planets.txt
drwxr-xr-x 1 root root 4.0K Oct 19 16:36 sample_data


In [ ]:
arr1 = np.zeros((10000,10000))

In [ ]:
np.savez("zeros",arr1)
np.savez("zeros_compressed",arr1)

In [ ]:
!ls -lh

total 1.5G
-rw-r--r-- 1 root root  85K Oct 21 17:13 many_arrays_compressed.npz
-rw-r--r-- 1 root root  90K Oct 21 17:09 many_arrays.npz
-rw-r--r-- 1 root root 1.6K Oct 21 17:02 planets_new.npy
-rw-r--r-- 1 root root 4.5K Oct 21 16:59 planets_new.txt
-rw-r--r-- 1 root root  257 Oct 21 16:52 planets_small.txt
-rw-r--r-- 1 root root 1.5K Oct 21 16:52 planets.txt
drwxr-xr-x 1 root root 4.0K Oct 19 16:36 sample_data
-rw-r--r-- 1 root root 763M Oct 21 17:16 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Oct 21 17:16 zeros.npz


#Stats with numpy

In [ ]:
arr = np.random.rand(100000,)

In [ ]:
np.amin(arr)

7.83073057342154e-06

In [ ]:
np.amax(arr)

0.999995644801203

In [ ]:
np.mean(arr)

0.499624964746868

In [ ]:
np.var(arr)

0.08335016185130105

In [ ]:
np.std(arr)

0.2887042809715524

In [ ]:
np.median(arr)

0.5003531785441369

In [ ]:
np.percentile(arr,50)

0.5003531785441369

In [ ]:
np.percentile(arr,30)

0.29883563131452506

In [ ]:
iqr = np.percentile(arr,75) - np.percentile(arr,25)
print(iqr)

0.4989796313341572


In [ ]:
%%time
quartiles = np.percentile(arr,[25,75])
print(quartiles)
iqr = quartiles[1] - quartiles[0]
print(iqr)

[0.24936716 0.74834679]
0.4989796313341572
CPU times: user 6.47 ms, sys: 0 ns, total: 6.47 ms
Wall time: 14.8 ms


In [ ]:
z_scores = (arr - np.mean(arr))/np.std(arr)
print(z_scores)

[-0.28472327 -0.61105565 -1.51748137 ...  1.094161    0.10572626
 -1.61705217]


In [ ]:
np.histogram(arr)

(array([10093,  9944, 10081,  9881,  9965, 10101, 10076,  9900,  9901,
        10058]),
 array([7.83073057e-06, 1.00006612e-01, 2.00005394e-01, 3.00004175e-01,
        4.00002956e-01, 5.00001738e-01, 6.00000519e-01, 6.99999301e-01,
        7.99998082e-01, 8.99996863e-01, 9.99995645e-01]))

In [ ]:
np.histogram(arr,bins=5)

(array([20037, 19962, 20066, 19976, 19959]),
 array([7.83073057e-06, 2.00005394e-01, 4.00002956e-01, 6.00000519e-01,
        7.99998082e-01, 9.99995645e-01]))

In [ ]:
np.histogram(arr,bins=[0,.25,.5,.75,1]) #num of points per bin


(array([25059, 24905, 25207, 24829]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
bins = [0,0.25,0.5,0.75,1]
np.digitize(arr,bins)  #tells corresponding bin that point belongs to

array([2, 2, 1, ..., 4, 3, 1])

In [ ]:
arr1 = np.random.randint(0,10,(10))
arr1

array([8, 6, 7, 7, 1, 3, 9, 1, 4, 4])

In [ ]:
bins=[0,6,10]
np.digitize(arr1,bins) #bydefault left is inclusive

array([2, 2, 2, 2, 1, 1, 2, 1, 1, 1])

In [ ]:
np.digitize(arr1,bins,right=True) #right is inclusive

array([2, 1, 2, 2, 1, 1, 2, 1, 1, 1])

In [ ]:
arr1 = np.random.randint(50,80,100)   #weights
arr2 = np.random.randint(150,185,100)  #heights
arr3 = np.random.randint(12,22,100)    #age

In [ ]:
np.concatenate((arr1,arr2,arr3)).shape    #takes 1st arg as tuple (arrays to concatenate)

(300,)

In [ ]:
np.vstack((arr1,arr2,arr3)).shape  #vertical stack

(3, 100)

In [ ]:
arr2d = np.vstack((arr1,arr2,arr3))
np.amin(arr2d,axis=1)  #min wt,ht,age

array([ 50, 150,  12])

In [ ]:
np.amax(arr2d,axis=1)

array([ 79, 184,  21])

In [ ]:
arr = np.random.rand(1000)

In [ ]:
np.cumsum(arr)  #returns sum of previous elements till that

array([  0.768858  ,   1.75333652,   2.48171077,   3.3791284 ,
         3.6729875 ,   4.52003299,   4.73628165,   5.67928661,
         6.62716681,   6.69184611,   7.11284445,   7.50234299,
         8.27689144,   8.50537559,   9.07576986,   9.40629636,
        10.22871152,  10.98955596,  11.49274474,  12.26047646,
        12.37895795,  12.77593607,  12.80828195,  13.59201054,
        13.88791247,  14.41088058,  14.87347036,  15.29645907,
        15.5560139 ,  15.5816645 ,  15.90370949,  16.84423329,
        17.23300982,  17.60141896,  18.51408976,  19.00688721,
        19.26924845,  19.41205584,  19.98207676,  19.99275542,
        20.03036293,  20.52482588,  20.59485104,  20.74636197,
        21.03064654,  21.7674308 ,  22.07611629,  22.41264331,
        23.29286435,  23.68440798,  24.63469911,  25.48868381,
        26.19732573,  27.06978467,  27.37835621,  27.41089293,
        27.59418287,  27.88044302,  28.85902911,  29.58560089,
        29.76042432,  30.12585011,  30.90688855,  30.96

#case study problem

In [ ]:
!head cric_data-200320-181217.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


In [ ]:
cric_data = np.loadtxt("/content/cric_data-200320-181217.tsv",skiprows=1)

In [ ]:
cric_data.shape

(225, 4)

In [ ]:
cric_data = cric_data[:,[1,2,3]]

In [ ]:
cric_data.shape

(225, 3)

In [ ]:
sachin = cric_data[:,0]
rahul  = cric_data[:,1]
india = cric_data[:,2]

In [ ]:
def stats(col):
  print("mean :",np.mean(col))
  print("median:",np.median(col))
  print("iqr:",np.percentile(col,75)-np.percentile(col,25))

In [ ]:
stats(sachin)

mean : 39.87555555555556
median: 27.0
iqr: 57.0


In [ ]:
stats(india)

mean : 220.79555555555555
median: 216.0
iqr: 98.0


In [ ]:
np.mean(cric_data,axis = 0)

array([ 39.87555556,  32.06222222, 220.79555556])

In [ ]:
np.median(cric_data,axis = 0)

array([ 27.,  22., 216.])

In [ ]:
np.percentile(cric_data,75,axis=0) - np.percentile(cric_data,25,axis=0)

array([57., 46., 98.])

In [ ]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [ ]:
sachin.shape

(225,)

In [ ]:
sachin_by_25s = sachin.reshape((9,25))

In [ ]:
np.mean(sachin_by_25s,axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [ ]:
np.mean(sachin[sachin>=100])

125.0

In [ ]:
np.mean(sachin[rahul<=10])

40.2112676056338